/**
 * Created by cuilanqing on 2017/5/22.
 */

/* splash页面图片相关 */
export const REQUEST_START_IMAGE_URL = 'REQUEST_START_IMAGE_URL';
export const RECEIVE_START_IMAGE_URL = 'RECEIVE_START_IMAGE_URL';

/* 主界面相关 */
// 1、获取最新story
export const REQUEST_LATEST_STORY_LIST = 'REQUEST_LATEST_STORY_LIST';
export const RECEIVE_LATEST_STORY_LIST = 'RECEIVE_LATEST_STORY_LIST';
// 2、获取往期story
export const REQUEST_PREVIOUS_STORY_LIST = 'REQUEST_PREVIOUS_STORY_LIST';
export const RECEIVE_PREVIOUS_STORY_LIST = 'RECEIVE_PREVIOUS_STORY_LIST';
// 3、获取story详情
export const REQUEST_STORY_DETAIL_INFO = 'REQUEST_STORY_DETAIL_INFO';
export const RECEIVE_STORY_DETAIL_INFO = 'RECEIVE_STORY_DETAIL_INFO';